name: Python application

on: [push,pull_request] 
permissions:
    contents: read

jobs:
  build: 
    runs-on: ubuntu-latets

    steps:
    - uses: actions/checkout@v4
    - name: Setup de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Instal·lar dependències         
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')  
    
