name: Python application

on: [pull_request] 
permissions:
    contents: read

jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Instal·lar dependències         
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Execució de test i code coverage
      run: |
        pytest test.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
    - name: Anàlisis de codi amb linter pylint
      run: |
        pylint $(git ls-files '*.py')  

    
